(in-package #:extrinsicl)

(defun install-cl (client environment)
  (install-special-operators client environment)
  (install-simple-function-aliases client environment)
  (install-simple-class-aliases client environment)
  (install-simple-constant-aliases client environment)
  (install-variables client environment)
  (install-environment-accessors client environment)
  (install-generic-environment-accessors client environment)
  (install-common-macros client environment)
  (install-loop client environment)
  (install-setf-functions client environment)
  (install-setf-expanders client environment))
